
all :
	@make -s -C pointer
	@make -s -C template
	@make -s -C intrusive
	@make -s -C metadata

clean :
	@make -s -C pointer   clean
	@make -s -C template  clean
	@make -s -C intrusive clean
	@make -s -C metadata  clean
